services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${GOBID_DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${GOBID_DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${GOBID_DATABASE_NAME:-mydatabase}
    ports:
      - ${GOBID_DATABASE_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GOBID_DATABASE_USER:-postgres} -d ${GOBID_DATABASE_NAME:-mydatabase}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    driver: local
